---
title: "Stocks_HMM"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r hmm}
library(ldhmm)
library(moments)
ts = ldhmm.ts_log_rtn("spx", on ="days")
sapply(0:10, function (drop) kurtosis(ldhmm.drop_outliers(ts$x, drop)))
ldhmm.ts_abs_acf(ts$x,drop =0 , lag.max =6)
ldhmm.ts_abs_acf(ts$x,drop =10, lag.max =6)


mu_1 = 0.0006
sigma_1 = 0.01
mu_2 = −0.0007
sigma_2 = 0.02
m = 2

param0=matrix(c(mu_1, sigma_1, mu_2, sigma_2), m, 2, byrow=TRUE)
gamma0=ldhmm.gamma_init(m)
h <- ldhmm(m, param0, gamma0, stationary=TRUE)
hd <- ldhmm.mle(h, ts$x, decode = TRUE, print.level =2)
hd@param
hd@gamma
hd@delta

ldhmm.ld_stats(hd)

hd@states.local.stats

ldhmm.ld_stats(hd)

ldhmm.calc_stats_from_obs(hd, drop=11)

ldhmm.oxford_man_plot_obs(hd)

```



```{r hmm_2}
states_prob <- t(as.data.frame(hd@states.global.stats))

write.csv(states_prob,"states_prob.csv")


```

```{r hmm_3}

hs<-ldhmm.simulate_state_transition(hd, init =100000)
kurtosis(hs@observations)

ldhmm.simulate_abs_acf(hd, n=100000, lag.max =1)

```